// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bomberman_backend.Data;

#nullable disable

namespace bomberman_backend.Migrations
{
    [DbContext(typeof(DatabaseContextcs))]
    [Migration("20250505120842_migration_0012")]
    partial class migration_0012
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainModels.Bomb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("explosionRadius")
                        .HasColumnType("integer");

                    b.Property<int>("fuseTime")
                        .HasColumnType("integer");

                    b.Property<string>("xCordinate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("yCordinate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bomb");
                });

            modelBuilder.Entity("DomainModels.ControllerLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("controllerLogs");
                });

            modelBuilder.Entity("DomainModels.Leaderboard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("hightScore")
                        .HasColumnType("integer");

                    b.Property<int>("totalGames")
                        .HasColumnType("integer");

                    b.Property<int>("totalWins")
                        .HasColumnType("integer");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("leaderboards");
                });

            modelBuilder.Entity("DomainModels.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HostUserIDId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostUserIDId");

                    b.ToTable("lobby");
                });

            modelBuilder.Entity("DomainModels.PowerUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Effect")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("powerup");
                });

            modelBuilder.Entity("DomainModels.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("DomainModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DomainModels.Player", b =>
                {
                    b.HasBaseType("DomainModels.User");

                    b.Property<int>("bombId")
                        .HasColumnType("integer");

                    b.Property<string>("characterColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("inLobby")
                        .HasColumnType("boolean");

                    b.Property<long>("lives")
                        .HasColumnType("bigint");

                    b.Property<int?>("lobbyId")
                        .HasColumnType("integer");

                    b.Property<int?>("powerUpId")
                        .HasColumnType("integer");

                    b.Property<long>("score")
                        .HasColumnType("bigint");

                    b.Property<int>("sessionIdId")
                        .HasColumnType("integer");

                    b.Property<int>("wins")
                        .HasColumnType("integer");

                    b.HasIndex("bombId");

                    b.HasIndex("lobbyId");

                    b.HasIndex("powerUpId");

                    b.HasIndex("sessionIdId");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("DomainModels.ControllerLogs", b =>
                {
                    b.HasOne("DomainModels.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DomainModels.Lobby", b =>
                {
                    b.HasOne("DomainModels.User", "HostUserID")
                        .WithMany()
                        .HasForeignKey("HostUserIDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostUserID");
                });

            modelBuilder.Entity("DomainModels.Player", b =>
                {
                    b.HasOne("DomainModels.Bomb", "bomb")
                        .WithMany()
                        .HasForeignKey("bombId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainModels.Lobby", "lobby")
                        .WithMany("Players")
                        .HasForeignKey("lobbyId");

                    b.HasOne("DomainModels.PowerUp", "powerUp")
                        .WithMany()
                        .HasForeignKey("powerUpId");

                    b.HasOne("DomainModels.Session", "sessionId")
                        .WithMany()
                        .HasForeignKey("sessionIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bomb");

                    b.Navigation("lobby");

                    b.Navigation("powerUp");

                    b.Navigation("sessionId");
                });

            modelBuilder.Entity("DomainModels.Lobby", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
