name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cleanup:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v4
      - name: Clean up Docker image
        run: | 
            docker stop Backend
            docker remove Backend
        
  build:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file bomberman-backend/Dockerfile --tag h3-backend-project:latest
  test:
      needs: build
      runs-on: "self-hosted"
      steps:
        - uses: actions/checkout@v4
        - name: Run the Docker image
          run: docker start h3-backend-project:latest -p 8080:8080 --name Backend
