name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file bomberman-backend/Dockerfile --tag my-image-name:$(date +%s)
      - uses: actions/checkout@v4
      - name: run the Docker image
        run: docker run . --file --file bomberman-backend/Dockerfile --tag my-image-name:$(date +%s)
